### ISSUE TITLE
DPI Scaling not set on RDP

### ISSUE THREAD

**Issue by johnarnold** [kmscode/mRemote3G#11]
When using RDP on a high DPI monitor, the desktop/GUI in the remote session is tiny.  The RDP client is not setting Windows' DPI scaling setting (e.g. at 175%) on the remote end.

Additional details on Scaling Level: 
http://blogs.msdn.com/b/rds/archive/2013/12/16/resolution-and-scaling-level-updates-in-rdp-8-1.aspx 

Are you using a specific version of MSTSC?  Can it be updated to a newer version (e.g. Windows 10)?

**Comment by johnarnold** [comment]
I noticed it does seem to work properly on "Full Screen"  just not on "Fit to Panel" or "Smart Size".

**Comment by kmscode** [comment]
Just for documentation purposes, what's your resolution/DPI?

The way mRemote works is it loads the RDP sessions via the MSTSCLib ActiveX control. This is made available by AxInterop.MSTSCLib.dll / Interop.MSTSCLib.dll. These ship with mRemote3G and are an export from a previous version (either mRemoteNG or the original mRemote). So I'm not entirely sure what RDP version these are based off of. I have already looked into updating these in a future release of 3G.

If I were to update these, I would need to update them and any associated code (which their may be some code changes required for scaling features) and require that RDP v8.1 be installed on the system in order to use 3G. This would effectively cut support to Windows 7 SP1 and later (which I'm 100% OK with).

No ETA, but still looking into this.

**Comment by kmscode** [comment]
Set milestone to 1.94. Would like to update the activex controls for the next release which I suspect would resolve this problem. 

It's also possible that some of the commits from [this mRemoteNG fork](https://github.com/karoberts/mRemoteNG) might also be helpful.

**Comment by kmscode** [comment]
@johnarnold did you have a chance to test 1.94.2 or the latest [prerelase build](https://github.com/kmscode/mRemote3G/releases/tag/1.94.2.40622)? Did this help at all?

Reopen the bug report if needed and please provide any testing results (good, bad or otherwise). Thanks!
