### ISSUE TITLE
Firefox as rendering engine for http

### ISSUE THREAD

**Issue by sauvesean** [kmscode/mRemote3G#12]
probably would be a lot of work, but would be great to see firefox as an available rendering engine for http/s.  Cisco Unified Communications typically all but requires it (at least the versions 10 and 11 I've worked on recently).  Since my main use of your software is for network administration, this would be awesome!!

**Comment by kmscode** [comment]
I checked out a few of the release notes for the last few versions of UCM... Should be good with IE10 or IE11 - which the current mRemote3G will emulate depending on your OS version and installed version of IE. So keep that in mind for now and ensure that IE is up to date. If you're on Win 7/8.1/10, with IE 10 or 11, you should be OK... Though I would recommend IE11 as it does function much better than 10 in general.

If you're on Win 8 (NOT 8.1, but the original 8), upgrade to 8.1 and IE11... MS wants to completely forget about Win 8 as quickly as possible and doesn't even offer IE11 for it.

mRemote3G will only work with IE9, IE10 or IE11.

Older versions of mRemote* supported a VERY old version of the Gecko rendering engine. Basically any newer version of Gecko wouldn't work when I attempted it. So I made the decision to beef up the IE code a little and removed the Gecko code. It could possibly be added back in in the future, but that would be a semi-significant effort as the removed code would need to be added back in and then (since it was a VERY old Gecko version) I'm assuming a lot of code changes from there to fix whatever wasn't working...

For reference:
da78efe1fa302ff72bf21d5d260f44eb8c7e1a88
a70ff99dec075fc785a3ebe72c5bd75a707acbf9
11a1f94e979cdb0f8823849c88fe0fbbbae40e40

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature

However, the latest version of mRemoteNG includes an updated Gecko Rendering Engine which may suit your needs:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.74
