### ISSUE TITLE
freeze after multiple connection

### ISSUE THREAD

**Issue by mighelon** [kmscode/mRemote3G#14]
Hi,
if you connect to some Windows Server 2012 R2 hosts quickly using RDP (double-clicking 3-4 or 5 servers), mRemote3G completely freezes the entire laptop, you cannot do anything for some minutes until it unfrees.
Thank you!

**Comment by kmscode** [comment]
mRemote3G is a user mode process. It's highly unlikely that there is something code related that is causing your problem when no one else reports this. Many users regularly connect to an entire folder of connections without issue. I personally tested connecting to a folder with 8 connections (right click on the folder ~> Connect) without issue. I then did that for multiple folders with varying number of connections. Again no problems.

I would recommend that you update all drivers on your system. I would start with the Video drivers, and then work through: network, sound (RDP will attempt to optionally bring remote sounds to the localhost), and chipset. In addition, you should update your BIOS if possible. Sometimes BIOS updates include CPU microcode fixes in case there is a problem with your specific CPU.

If you have an Intel CPU and motherboard that uses multiple Intel components, their [driver update utility](http://www.intel.com/content/www/us/en/support/detect.html) is very convenient.

**Comment by kmscode** [comment]
@mighelon Try [1.94.1](https://github.com/kmscode/mRemote3G/releases/tag/1.94.1) and let me know if you're still having problems (in addition to the driver updates, etc). There were some compiler option changes that may impact your problem.

**Comment by mighelon** [comment]
thank you very much for your precious information
I'm using 1.94 since 2 days and everything seems to work correctly
I'll let you know if some issues still persist

m.

**Comment by MilanDasek** [comment]
I have exactly same experience/problem. Latest version and when I opened 4 RDPs, my laptop froze. I have Windows 10 x64 Pro. This is exactly same behavior as original client has.

**Comment by federicozanardi** [comment]
on 1.94.1 I still have this issue randomly
mremote freeze for 10-15 secs then return usable
no error in logs
this happens on win 10 x64

**Comment by mighelon** [comment]
Same behavior on 1.94 even for me
Connecting to WinSrv 2012 and 2012 R2

m.

**Comment by kmscode** [comment]
@mighelon @MilanDasek @federicozanardi Could you please attach the mRemote3G.log for review?

I still recommend driver updates as well.

**Comment by mighelon** [comment]
timestamp of my test:
2016-01-27 13:48
[mRemote3G.zip](https://github.com/kmscode/mRemote3G/files/106793/mRemote3G.zip)

**Comment by federicozanardi** [comment]
1.94.2 same issue

**Comment by kmscode** [comment]
@federicozanardi Could you please attach your mremote3g.log for review? 

I'm not able to reproduce this at all... But I'll try to do some more tests with only Win2012 system (I was testing with some 2012 systems, a few 2008 and a number of putty sessions).

**Comment by federicozanardi** [comment]
[mRemote3G.zip](https://github.com/kmscode/mRemote3G/files/112547/mRemote3G.zip)

I'm pretty sure that issue is mostly caused by specific client OS (win 10)
other my colleagues with same OS have same issue

**Comment by kmscode** [comment]
Nothing much in the log. 

I run this personally on Win 10 Enterprise x64. I have a few other users that I know running it on the same OS. No problems.

When it hangs, can you open task manager -> details tab -> right click on the mRemote3G process -> Create Dump file.
Please upload the dump and the log from the timeframe of the dump.

Thanks!

**Comment by kmscode** [comment]
PS - I might need to create a debug build to make the dump more readable/usable. Though in troubleshooting some past issues with this code base, some problems didn't occur with debug builds.

**Comment by federicozanardi** [comment]
when it freezes , the mouse is completely stuck and no keybord input is processed.
i can take dump of the process only when it unfreezes, ok?

**Comment by njeske** [comment]
I'm experiencing this same issue as well.  Windows 10 Enterprise x64 build 1151.  When connected to four RDP sessions (all 2012r2 if that's relevant) my laptop completely froze up for about 60 seconds.  Within 10 seconds of the freeze starting, my fans all went to 100%.  Since the laptop was frozen, I was unable to open Task Manager to see if it was the CPU ramping up that caused the fan speed to increase, so it could have been either CPU or GPU.  I'll include my basic system specs below to maybe help narrow down a specific hardware or driver that may be having an issue.  This laptop can switch between the Intel and Nvidia GPUs, but only the Nvidia GPU was active during the lockup since I'm docked and running my external monitors.  All drivers for my hardware are fully up to date as of 1/31.

Lenovo W541
Intel Core i7-4810MQ
32GB DDR3
Nvidia Quadro K2100M
Intel HD Graphics 4600

**Comment by kmscode** [comment]
Thanks @njeske and @federicozanardi 

@njeske I have very similar specs on my laptop - Dell Precision 4800 (which has AMD/Intel switchable graphics). I have a few users with 4600's. None of us have these types of problems. Seems like a system problem more than anything else. 

I have to setup a few more 2012r2 VMs to test this a little better, but I can't reproduce it as of yet.

The only other thing that I can think of at the moment, would be to get a perfmon trace with basically all CPU, Memory, Disk, Process and Network metrics when the problem occurs. But that will really just show a little bit what (CPU, a different process, etc) the problem is and not so much where the problem is (in the code or on that system)...

**Comment by njeske** [comment]
If I get a chance to run a perfmon for you in the next day or so I will.  Maybe it will help, maybe not, but at the very least it will be some additional data.  For what it's worth, I have been running mRemote3G for the last several hours and only had the lockup issue once.  I typically have anywhere from 4-10 RDP sessions open at a time.

I had an M4800 myself up until a couple of months ago.  Had nothing but problems with AMD FirePro drivers trying to drive 4k monitors.  Switched over the W541 with the same specs, except for the Quadro rather than the FirePro, and it's been rock solid.  Not to mention lighter, thinner, and smaller PSU.

**Comment by njeske** [comment]
Just had mRemote3G lockup, but not due to too many connections.  Maybe this will be somewhat repeatable by others.  I had the same instance of mRemote3G open for about 6 hours, never more than 2-3 connections open at a time.  While I had just 2 connections open, I went to the "View" menu, and clicked "External Tools Toolbar."  Immediately, my RDP connections went into a reconnecting state (black screen), my mouse and keyboard froze up, and my about 15 seconds later my laptop fans ramped up to full speed.  After about a minute, the mouse was usable again, but clicks were taking about 10 seconds to register.  I managed to get Task Manager open and kill mRemote3G, which made everything return to normal.  Oh, and the "External Tools" toolbar never showed up.

What I found most interesting, is that Task Manager reported only 1-2% CPU usage for mRemote3G, which (to the best of my knowledge) would seem to indicate the GPU is what caused the system fans to speed up.

Final note, this is 100% repeatable for me.  After re-launching mRemote3G, opened a couple of RDP sessions, click to enable the "External Tools" toolbar and got the exact same result.

**Comment by kmscode** [comment]
@njeske thanks! Sounds like it could be related to #16. Not sure what would be using the GPU specifically... But that is interesting...

**Comment by kmscode** [comment]
@njeske try [this build](https://github.com/kmscode/mRemote3G/releases/tag/1.94.2.34463) and let me know if you can still reproduce the problem.

**Comment by federicozanardi** [comment]
tried last version, a freeze occurred after 30 secs from opening :(

**Comment by kmscode** [comment]
@federicozanardi After opening connections to a few hosts, or just from opening the app?

**Comment by njeske** [comment]
I'm working from home today after taking my son to a doctor's appointment.  I'll try the new build as soon as I get a chance and post back here.

**Comment by federicozanardi** [comment]
it has happened after the fourth connection

**Comment by njeske** [comment]
I had a similar experience as @federicozanardi.  I opened six RDP connections, to a mix of 2008R2 and 2012R2 servers.  One the seventh connection attempt, the program locked up and my fans went nuts.  It wasn't the same type of lockup as when I tried to open the "external tools" toolbar though, as I was able to easily open Task Manager, see that mRemote3G had one of my CPU cores maxed out, and kill it.  For what it's worth, I did test enabling the "external tools" toolbar from the "view" menu, and it worked without any issues.

**Comment by jcefoli** [comment]
I never believed all of you, but this just happened to me.  I don't have 100% accurate steps to reproduce, but it seems to be semi-reproducible if you connect to a 2012 R2 server and then right click the connection tab and reconnect a few times in a row. I can reproduce an issue where the RDP frame just completely turns black when I right click and reconnect. Clicking around mRemote3G usually either hangs just the app or my entire system.

**Comment by mdw2** [comment]
Thank you so much for developing MR3!  I was exploring other programs because of this exact issue, but will stay with MR3.  This issue started happening in MRNG with the introduction of 2012r2 RDP servers (i.e. no issue with 2008r2 servers).  Usually after the 6th 2012r2 RDP connection i get 'RDP disconnected!  Failed ... Error code 4360' - no hanging.  When the issue happens, I can continue to RDP to 2008r2 servers without connection failed message.  If I close a couple of 2012r2 RDP sessions, I can then open the last 2012r2 session that failed.  I'm currently using version 1.94.2.34463.  I've tried this on Win7, Win8, and Win10 on different computers and get the same results.

I've tried jcefoli suggestion but it didn't resolve the issue for me.

**Comment by jcefoli** [comment]
My suggestion wasn't to fix it. My suggestion seems to reproduce the issue. I may have a workaround though...

In the config panel, set "Cache Bitmaps" to No. After I did that, I don't get the black screen issue or any system lockups. Perhaps mtremote does something to exacerbate the problem. Not sure if this is an mRemote3G issue or an overall RDP issue: http://www.gfisk.com/remote-desktop-black-screen/ 

My 2012 R2 servers are fully patched and I still have the freeze/black screen issue when I have Cache Bitmap enabled

**Comment by mdw2** [comment]
Setting  "Cache Bitmaps" to No did not resolve the issue for me.  To test further, I was able to open 12 2012r2 connections using mstsc.exe.

**Comment by federicozanardi** [comment]
I have performed few tests and it seems to workaround the bug!
I have opened 13 sessions together without freezes!!!

**Comment by njeske** [comment]
I'd like to try this out, but I can't seem to figure out where the bitmap caching setting is.

**Comment by kmscode** [comment]
![cachebitmaps](https://cloud.githubusercontent.com/assets/16654335/13260714/ba2a4846-da2a-11e5-880e-c35efcffc22a.png)

**Comment by njeske** [comment]
Thanks.  I was looking all of the mRemote3G settings window for it.  Didn't realize it was connection specific.  I used Notepad++ to edit the config file to change all of the CacheBitmaps="True" to CacheBitmaps="False".  I currently have 10 Windows 2012 R2 RDP sessions open without getting the 3334 error or any freezes.

**Comment by Zixyar** [comment]
Don't know if this could help and maybe @kmscode already knows, but RDP session connecting to 2012R2 servers eats up to 100/150Mb RAM on the client if persistent bitmap cache is enabled, reducing to about 1/3 disabling it, even with default mstsc client.

**Comment by kmscode** [comment]
Thanks @Zixyar. I'll see about changing the cache bitmaps default to no/false!

**Comment by kmscode** [comment]
If you're still having problems, please test with:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.74

And report a new bug as needed:
https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug

Thanks!
