### ISSUE TITLE
Request: update internal vnc viewer

### ISSUE THREAD

**Issue by sercon** [kmscode/mRemote3G#35]
It would be handy if the internal vnc viewer would be updated to support the latest realvnc/tightvnc/ultravnc protocols....

**Comment by kmscode** [comment]
The vnc implementation in mRemote is a slightly customized version of [VncSharp](https://github.com/humphd/VncSharp). It already supports [RFB Protocol 3.8](https://en.wikipedia.org/wiki/RFB_protocol).

Could you clarify on what might be missing?

**Comment by sercon** [comment]
Certainly:
When connecting to a (real-)vnc server with these specs:
VNC Server http://www.realvnc.com/:
- 5.0.3 (r97046) - Built on Oct  2 2012 16:57:46, 64bit build
- Mode: Service Mode
- Users connected: 1
- Authentication: VNC password
- Encryption: Prefer off

we receive the following error:
Opening connection failed!
VncSharp.VncProtocolException: Unable to connect to the server. Error was: The server is using an unsupported version of the RFB protocol. The server is using version 4.1 but only version 3.x is supported. ---> System.NotSupportedException: The server is using an unsupported version of the RFB protocol. The server is using version 4.1 but only version 3.x is supported.
   at VncSharp.RfbProtocol.ReadProtocolVersion()

**Comment by kmscode** [comment]
3.8 is the latest official documented version of the RFB protocol as far as I'm aware:
https://www.realvnc.com/docs/rfbproto.pdf
https://tools.ietf.org/html/rfc6143

But I guess they just stopped documenting the protocol???

**Comment by jcefoli** [comment]
RealVNC created their own proprietary version 4+ of the RFB protocol. Since it's closed source and the protocol is not documented, it's not possible for mRemote3G to work with it.

As a workaround, You can either change the server to TightVNC or UltraVNC, or download the VNC Viewer standalone executable from RealVNC and see if you can configure it as an external tool.

**Comment by kmscode** [comment]
Looks like there is a [known issue with upstream vncsharp](https://github.com/humphd/VncSharp/issues/2) - someone hacked it and it seems to work. 

@jcefoli - any more details or references about this? Thanks for the info!!!

Since it's closed source/proprietary, will not support. @jcefoli 's recommendations are 100% valid.
