### ISSUE TITLE
VNC Connection copy and paste

### ISSUE THREAD

**Issue by mrcwatling** [kmscode/mRemote3G#37]
Hi,

I and the other techs here have an issue when we connect using mRemote3G to a machine with VNC and copy the contents of a document to the clipboard then come back to our local computer and paste we get lots of (50 or more) CR LF between each line so the document ends up to be thousands of lines long.

We are running TightVNC 2.7.10 as the server on machines and it happens on all machines on our network when using mRemote3G. If we use TightVNC's viewer or another viewer its fine.

Any way that we can either change the VNC viewer that is used in mRemote3G or have this corrected?

Thanks

**Comment by kmscode** [comment]
The vnc implementation in mRemote is a slightly customized version of [VncSharp](https://github.com/humphd/VncSharp).

I don't really use VNC at all, so I haven't encountered this. 

I'll try to rebuilt the library and possible merge in the latest changes from from the main/upstream vncsharp project. That should be semi-quick and easy...

Otherwise I'd have to look into it further, but no ETA.

**Comment by kmscode** [comment]
If you're still having problems, please test with:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.75Aplha1
(some changes to the VncSharp lib in this release)

And report a new bug as needed:
https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug

Thanks!
