### ISSUE TITLE
Could we integrate more with putty ---> xml to hold ssh tunneling info

### ISSUE THREAD

**Issue by wardcomm** [kmscode/mRemote3G#41]
Could we integrate more with putty ---> xml to hold ssh tunneling info, without using putty gui.

**Comment by kmscode** [comment]
PuTTY stores its sessions within the registry.

Could you please provide some further details as to what you were thinking about?

If you're looking for an easy way to get to the PuTTY sessions editor from within mRemote3G, it's currently in Options > Advanced > Lauch PuTTY:
![launchputty](https://cloud.githubusercontent.com/assets/16654335/13712580/7459b0f2-e792-11e5-8316-7b6168eee926.png)

But I could look into adding this on the Tools Menu for really easy access to it. I would prefer that PuTTY continue to save/write PuTTY's configuration items (don't want to reinvent the wheel or break something that is effectively shared outside of mRemote3G).

**Comment by Silent-Joker** [comment]
You might be able to look into Kitty code.  I replace Putty.exe with kitty.exe and use the local files for sessions instead of registry.  works like a charm.  I'm not sure if they would let you include it in your build but there is the code base you may be able to see how they set it up.  I also must have the anti idle function.  I usually set this up with the space bar key.  but 2 very nice features that makes Mremote way better to use.

http://www.9bis.net/kitty/?page=Portability

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature

See:
https://mremoteng.atlassian.net/browse/MR-357
https://mremoteng.atlassian.net/browse/MR-404
