### ISSUE TITLE
Add keyboard shortcuts to switch between tabs

### ISSUE THREAD

**Issue by 0xAalaoui** [kmscode/mRemote3G#44]
This is a feature request to have a shortcut that would help to quickly change between the different tabs in the application.

**Comment by kmscode** [comment]
The previous version (mRemoteNG) attempted to implement this functionality. It was never fully released as it wasn't functional and caused multiple problems. It was removed from mRemote3G in f2d4478b7fd32cb1ef2bc5afc98cfc3666ed3faf

Removed due to the following reasons:
1. Crashes (semi-regularly)
2. "Beta" option from 1.73 (never released) that doesn't work (on Windows 10 at least)
3. A few bugs were reported for it in the old bug tracking system:
https://mremoteng.atlassian.net/browse/MR-624
https://mremoteng.atlassian.net/browse/MR-687
https://mremoteng.atlassian.net/browse/MR-752
(and possibly more)
4. After reviewing the bug reports and other info, I feel it's a bad idea. All keyboard input should go to the connected session (while "active"). Otherwise a mouse click would be required to have mRemote be the active Window. In which case, just click the desired tab.
