### ISSUE TITLE
Putty windows are not integrated correctly

### ISSUE THREAD

**Issue by kjellml** [kmscode/mRemote3G#5]
Putty windows are not fully integrated into the panels of the mremote3G GUI.

There's some of the putty border showing as you can see in my screenshot.

OS: Windows 10 Home (1511)
Mremote3G: 1.91.5848.31042 (using provided PuttyNG.exe)

![mremote3g](https://cloud.githubusercontent.com/assets/16583280/12156180/b30a592e-b4c9-11e5-976c-1a642af49aaf.jpg)

**Comment by kaymer327** [comment]
I have the same problem. I haven't figured it out yet. It doesn't seem to impact any functionality other than not looking "perfect".

**Comment by cookandy** [comment]
This is also affecting the window coming to the foreground correctly for me.  Steps to reproduce:

1. Open mRemote3G in a Window (not full screen)
2. Open Chrome (or some other window), make sure it's in front of mRemote3G, but so that you can still see the application.
3. Click on mRemote3G - everything works fine. The application comes to the foreground as expected.
4. Open an SSH session in mRemote3G (doesn't seem to affect RDP connections)
5. Bring Chrome to the foreground
6. Try to click in the black area (the SSH window) to try to bring mRemote3G to the foreground
7. You'll notice mRemote3G does not come to the foreground

See https://github.com/kmscode/mRemote3G/issues/24 for more info.

**Comment by kmscode** [comment]
Yes. It does seem that this is related to #24. 

I did look into this for a bit, but couldn't really narrow it down any further...

It doesn't seem to be a problem with the updated puttyng build, since if I put the new puttyng into old mremoteng, it works fine. Also if I put the old puttyng into the new mremote3g, the problem still occurs. However, I one point I backed out of many changes in 3g around the area of code where the connection tab/window is generated and the problem still occurred. A bit stumped, but I'll keep at this. 

Will try to fix this one ASAP.

**Comment by kmscode** [comment]
Made some minor progress, but also seem to have some how caused more problems (at least on my system).

**Comment by kmscode** [comment]
Pretty sure I found the offending code. (FINALLY!!!!)  :satisfied:

Tagging this one for 1.94.3

**Comment by cookandy** [comment]
Fantastic!  Looking forward to the release.  :)

**Comment by kmscode** [comment]
If you're still having problems, please test with:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.74

And report a new bug as needed:
https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug

Thanks!
