### ISSUE TITLE
Disable the confCons.xml password protection

### ISSUE THREAD

**Issue by mobashua** [kmscode/mRemote3G#65]
Hello,

I want to generate periodically in php the confCons.xml file (list of servers).
And after that, I would like to import this file to mRemote3G, without providing a password (no protection).
Is there any way of doing that ? Would that be by tweaking the "protected" attribute ?

Thanks in advance,
M

**Comment by kmscode** [comment]
@mobashua due to the sensitive nature of the data included in the confCons.xml, reducing security of it is not something that I'd be interested in doing or looking into - so I don't have an answer to your question. In addition, all dev efforts are now focused on mRemoteNG and are are looking at *increasing* security of confCons.xml.
